"""Outbound export of PersonalClaw entities into external harness formats.

This is the OPPOSITE direction from the pack importer and from the read-only inbound
adapters: here we *write into another tool's directory*. That makes four rails
load-bearing, and every one of them fails CLOSED:

1. **Explicit dest confirmation.** :func:`export_entities` refuses unless the caller passes
   ``confirm_dest=True``. Nothing is ever "auto-installed" into another tool's config.
   :func:`default_dest_dir` only *suggests* the canonical location.
2. **Containment.** A rendered file's relative path is validated twice — once when a
   renderer derives it from an entity name (:func:`_slug`), once again against the resolved
   destination root (:func:`_resolve_target`). ``../``, absolute paths and path separators
   in a slug are refused, so an entity name can never steer a write outside ``dest_dir``.
3. **Content redaction.** Every rendered file's text is scanned with
   :func:`packs.build._scan_component` — the SAME two detectors (``security.redact`` +
   ``guardrails.scan_outbound``) the pack exporter uses, imported rather than forked. A hit
   BLOCKS the whole export before any file is written; a credential is never rewritten into
   someone else's prose and never lands on disk.
4. **No clobber.** We only ever replace a file we wrote ourselves, identified by the
   :data:`PROVENANCE_MARKER` trailer. A user's own agent definition at the same path is
   refused, never overwritten — and ONE such file refuses the whole export, naming every
   file in the way at once.

The preview and the write share one plan (:func:`_plan`): for every file, where it lands and
what writing it would do there (:data:`FILE_NEW`, :data:`FILE_SAME`, :data:`FILE_REPLACE`,
:data:`FILE_THEIRS`). So the list a user confirms is the list the write acts on, decided by the
same rule, and read again from the disk at the moment of writing.

The rendering contract is one-shot: **an export surface, not a sync system**. Drift
after the write is the recipient tool's problem, which is exactly why the render must be
deterministic — the same entities render byte-identical bytes on every run, so a
re-export is a no-op diff. No timestamps, no machine paths, no dict-iteration order
reaches the output; roster order is sorted. ``tests/fixtures/external_formats_golden/``
pins that promise per format.
"""

from __future__ import annotations

import re
from collections.abc import Callable, Sequence
from dataclasses import dataclass, field
from pathlib import Path, PurePosixPath
from typing import TYPE_CHECKING, Any, Union

from personalclaw.agents.marketplace import AgentDefinition
from personalclaw.atomic_write import atomic_write

if TYPE_CHECKING:
    from personalclaw.config.loader import AgentProfile

# ── Rendering primitives ──────────────────────────────────────────────────────

#: Appended as the last line of every rendered file. Two jobs: it tells a human where the
#: file came from, and it is how :func:`export_entities` recognises a file as OURS and
#: therefore safe to replace. Deliberately constant — a version or timestamp here would
#: break the byte-identical guarantee and make every re-export a spurious diff.
PROVENANCE_MARKER = "<!-- generated by personalclaw: outbound entity export -->"

#: The three ``installKind`` values. Plain strings, not an ``Enum``: an enum member
#: no writer ever produces is exactly the declared-but-inert surface the repo censuses.
INSTALL_KIND_PER_AGENT = "per-agent"
INSTALL_KIND_ROSTER = "roster"
INSTALL_KIND_PLUGIN = "plugin"

_SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9._-]{0,62}$")


@dataclass(frozen=True)
class ExportSkill:
    """A skill to export near-verbatim — it is already the standard skill-catalog shape."""

    slug: str
    text: str


#: What a renderer accepts. Agents render into every format; a skill only makes sense in
#: the SKILL.md format, and the other renderers refuse it loudly rather than skipping it
#: (a silently-skipped entity is an export that looks like it worked).
Entity = Union[AgentDefinition, ExportSkill]


@dataclass(frozen=True)
class RenderedFile:
    """One file a renderer produced: a POSIX-relative path under ``dest_dir`` plus text.

    ``entities`` names what was rendered into it — one agent or skill for a per-entity format,
    every agent for a roster — so a caller can tie a file back to what the user picked without
    re-deriving how a format names its files.
    """

    relpath: str
    text: str
    entities: tuple[str, ...] = ()


@dataclass(frozen=True)
class ExternalFormat:
    """The external-format contract, field-for-field.

    ``installKind`` keeps the contract's spelling deliberately — this is a declared contract
    name, not a local variable. ``dest`` is the *canonical documented* location (a template
    for the per-entity kinds); the actual write target is always the caller's confirmed
    directory, never this string.
    """

    name: str
    installKind: str  # noqa: N815 — the contract's field name
    dest: str
    render: Callable[[Sequence[Entity]], list[RenderedFile]]


# ── Errors (all fail CLOSED, all name the offending thing) ────────────────────


class ExportRefused(Exception):
    """Base class — an export that did not happen, and said why."""


class DestNotConfirmed(ExportRefused):
    """The caller did not explicitly confirm the destination directory."""


class ExportPathRefused(ExportRefused):
    """A rendered path would escape ``dest_dir`` (or a slug is not a safe file name)."""


class ExportClobberRefused(ExportRefused):
    """The destination holds files we did not write. We never overwrite one.

    Every such file is named in the one refusal: an export that stopped at the first clash would
    send the user back for each of the others in turn.
    """

    def __init__(self, targets: list[Path]):
        self.targets = targets
        if len(targets) == 1:
            what, it, them = f"{targets[0]} (not written by PersonalClaw)", "it is", "it"
        else:
            listed = ", ".join(str(t) for t in targets)
            what = f"{len(targets)} files PersonalClaw did not write: {listed}"
            it, them = "they are", "them"
        super().__init__(
            f"Refusing to overwrite {what}. Nothing is exported while {it} there: leave {them} "
            "out to export the rest."
        )


@dataclass(frozen=True)
class BlockedRender:
    """One rendered file the content layer refused to let leave."""

    relpath: str
    reason: str
    categories: tuple[str, ...] = ()


#: What each content-scan category is, in the words a refusal uses.
_BLOCKED_WORDS = {
    "credential": "what looks like a credential",
    "exfil_url": "a link that could send data out",
}


def _blocked_phrase(blocked: BlockedRender) -> str:
    words = [_BLOCKED_WORDS[c] for c in blocked.categories if c in _BLOCKED_WORDS]
    if words:
        return f"{blocked.relpath} holds {' and '.join(words)}"
    return f"{blocked.relpath} could not be checked ({blocked.reason})"


class ExportBlocked(ExportRefused):
    """The content layer found a credential in rendered output. Nothing was written."""

    def __init__(self, blocked: list[BlockedRender]):
        self.blocked = blocked
        detail = "; ".join(_blocked_phrase(b) for b in blocked)
        super().__init__(
            f"Nothing is exported: {detail}. Remove it, or leave it out to export the rest."
        )


class ExportWriteFailed(Exception):
    """A write failed part-way. Not an :class:`ExportRefused`: this export DID start, so what it
    already wrote is named rather than left for the user to discover."""

    def __init__(self, target: Path, written: list[Path], cause: OSError):
        self.target = target
        self.written = list(written)
        reason = cause.strerror or type(cause).__name__
        if self.written:
            done = ", ".join(str(p) for p in self.written)
            count = "1 file was" if len(self.written) == 1 else f"{len(self.written)} files were"
            tail = f" {count} written before it stopped: {done}."
        else:
            tail = " Nothing was written."
        super().__init__(f"Could not write {target}: {reason}.{tail}")


@dataclass
class ExportResult:
    """What an export actually did — the absolute paths written, in render order, and the files
    already there byte-identical, which were left as they were."""

    format_name: str
    dest_dir: Path
    written: list[Path] = field(default_factory=list)
    unchanged: list[Path] = field(default_factory=list)


# ── Helpers ───────────────────────────────────────────────────────────────────


def _slug(name: str) -> str:
    """Validate an entity name as a file-name component. Raises rather than sanitising.

    Sanitising a hostile name (``../evil`` → ``evil``) writes a file the user never named,
    at a path they cannot predict. Refusing is the only honest answer, and it is the FIRST
    of two independent containment checks (:func:`_resolve_target` is the second).
    """
    slug = (name or "").strip()
    if not _SLUG_RE.match(slug):
        raise ExportPathRefused(
            f"unsafe entity name for a destination file: {name!r} "
            "(expected ^[a-z0-9][a-z0-9._-]{0,62}$ — no separators, no '..', not absolute)"
        )
    return slug


def _yaml_scalar(value: str) -> str:
    """Emit a single-line YAML scalar, quoted only when it must be.

    Frontmatter is the part an external tool parses; a description carrying ``:`` or a
    leading ``#`` would break its loader (i.e. the file would not load at all).
    """
    text = " ".join(str(value).split())  # collapse newlines/tabs: frontmatter is one line
    if not text:
        return '""'
    needs_quote = text[0] in "#&*!|>%@`'\"[]{}," or ": " in text or text.endswith(":")
    if needs_quote:
        return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return text


def _body(defn: AgentDefinition, *, skills_heading: str = "## Skills") -> str:
    """The persona body: operating rules, then voice, then declared skills.

    ``skills_heading`` demotes one level inside the roster format, where each agent already
    owns an ``##`` heading and a second ``##`` would read as a sibling section.

    ``mcp_servers`` is deliberately NOT rendered. It is a free-form dict whose values can
    carry env values or headers — the one field on an AgentDefinition that could plausibly
    hold a credential — and a foreign tool cannot consume our MCP shape anyway. Excluding
    it structurally beats redacting it after the fact.
    """
    parts: list[str] = []
    if defn.system_prompt.strip():
        parts.append(defn.system_prompt.strip())
    if defn.voice.strip():
        parts.append(defn.voice.strip())
    skills = [s.strip() for s in defn.skills if isinstance(s, str) and s.strip()]
    if skills:
        seen: dict[str, None] = dict.fromkeys(skills)  # de-dup, declared order preserved
        lines = [skills_heading, ""]
        lines += [f"- {s}" for s in seen]
        parts.append("\n".join(lines))
    return "\n\n".join(parts)


def _document(front: list[str], body: str) -> str:
    """Assemble frontmatter + body + provenance trailer with a fixed byte layout."""
    out = ["---", *front, "---", ""]
    if body:
        out += [body, ""]
    out.append(PROVENANCE_MARKER)
    return "\n".join(out) + "\n"


def agent_from_profile(name: str, profile: AgentProfile) -> AgentDefinition:
    """One of the user's agents (a profile in their config) in the shape the renderers take.

    Only what a renderer writes travels: the name, the description, the instructions, the voice
    and the skill names. The model, tools, triggers and approval mode stay with PersonalClaw —
    each names something only this installation can resolve (see
    :func:`render_claude_code_agents`).
    """
    return AgentDefinition(
        name=name,
        description=profile.description,
        system_prompt=profile.system_prompt,
        voice=profile.voice,
        skills=[s for s in profile.skills if isinstance(s, str)],
    )


def _agents_only(entities: Sequence[Entity], fmt_name: str) -> list[AgentDefinition]:
    bad = [e for e in entities if not isinstance(e, AgentDefinition)]
    if bad:
        raise ExportRefused(
            f"format {fmt_name!r} renders agents only; got "
            f"{', '.join(type(e).__name__ for e in bad)}"
        )
    if not entities:
        raise ExportRefused(f"format {fmt_name!r}: nothing to export")
    return list(entities)  # type: ignore[arg-type]


# ── Renderers ─────────────────────────────────────────────────────────────────


def render_claude_code_agents(entities: Sequence[Entity]) -> list[RenderedFile]:
    """One markdown file per agent, in the external per-agent agent-definition shape.

    Frontmatter carries ``name`` and ``description``, the two keys the format requires to load,
    and nothing else. It deliberately does NOT emit a ``tools:`` key: PersonalClaw's tool names
    are not the recipient's, so any value we wrote there would be invented — and an invented
    allowlist would silently narrow the exported agent's abilities. Omitting the key is the
    format's documented "inherit the caller's tools" default. Nor a ``model:`` key: an agent's
    model names one of THIS installation's models, which the recipient resolves against its own
    model names, so writing ours would pin the exported agent to a model it cannot find. Omitted,
    the recipient runs it on its own default. Declared skills go in the body instead, where an
    unknown key cannot break the recipient's frontmatter parse.
    """
    out: list[RenderedFile] = []
    for defn in _agents_only(entities, "claude-code-agents"):
        slug = _slug(defn.name)
        front = [f"name: {_yaml_scalar(defn.name)}"]
        front.append(f"description: {_yaml_scalar(defn.description or defn.name)}")
        out.append(RenderedFile(f"{slug}.md", _document(front, _body(defn)), (defn.name,)))
    return out


def render_cursor_rules(entities: Sequence[Entity]) -> list[RenderedFile]:
    """The whole roster as ONE rules file (cursor-rules is roster-kind).

    Agents are sorted by slug, so the same roster renders identically no matter what order
    the caller happened to enumerate it in.
    """
    agents = sorted(_agents_only(entities, "cursor-rules"), key=lambda d: _slug(d.name))
    front = [
        f"description: {_yaml_scalar(f'PersonalClaw agent roster ({len(agents)} agents)')}",
        "globs:",
        "alwaysApply: false",
    ]
    sections: list[str] = []
    for defn in agents:
        block = [f"## {defn.name}", ""]
        if defn.description.strip():
            block += [" ".join(defn.description.split()), ""]
        body = _body(defn, skills_heading="### Skills")
        if body:
            block += [body, ""]
        sections.append("\n".join(block).rstrip())
    body = "\n\n".join(sections)
    names = tuple(defn.name for defn in agents)
    return [RenderedFile("personalclaw-roster.mdc", _document(front, body), names)]


def render_skill_md(entities: Sequence[Entity]) -> list[RenderedFile]:
    """A ``skills/<slug>/SKILL.md`` per entity.

    An :class:`ExportSkill` ships near-verbatim — it already IS the standard shape, so
    re-rendering it would only risk mangling it. We append the provenance trailer (and a
    trailing newline) and nothing else, which keeps the write idempotent.
    """
    if not entities:
        raise ExportRefused("format 'skill-md': nothing to export")
    out: list[RenderedFile] = []
    for entity in entities:
        if isinstance(entity, ExportSkill):
            slug = _slug(entity.slug)
            text = entity.text if entity.text.endswith("\n") else entity.text + "\n"
            if PROVENANCE_MARKER not in text:
                text = f"{text}\n{PROVENANCE_MARKER}\n"
            out.append(RenderedFile(f"skills/{slug}/SKILL.md", text, (entity.slug,)))
        elif isinstance(entity, AgentDefinition):
            slug = _slug(entity.name)
            front = [
                f"name: {_yaml_scalar(entity.name)}",
                f"description: {_yaml_scalar(entity.description or entity.name)}",
            ]
            text = _document(front, _body(entity))
            out.append(RenderedFile(f"skills/{slug}/SKILL.md", text, (entity.name,)))
        else:
            raise ExportRefused(f"format 'skill-md': unsupported entity {type(entity).__name__}")
    return out


# ── Registry ──────────────────────────────────────────────────────────────────

CLAUDE_CODE_AGENTS = ExternalFormat(
    name="claude-code-agents",
    installKind=INSTALL_KIND_PER_AGENT,
    dest="~/.claude/agents/{slug}.md",
    render=render_claude_code_agents,
)

CURSOR_RULES = ExternalFormat(
    name="cursor-rules",
    installKind=INSTALL_KIND_ROSTER,
    dest=".cursor/rules/personalclaw-roster.mdc",
    render=render_cursor_rules,
)

SKILL_MD = ExternalFormat(
    name="skill-md",
    installKind=INSTALL_KIND_PLUGIN,
    dest="<dir>/skills/{slug}/SKILL.md",
    render=render_skill_md,
)

#: Every v1 format, keyed by ``name``. Insertion order is the presentation order.
EXTERNAL_FORMATS: dict[str, ExternalFormat] = {
    fmt.name: fmt for fmt in (CLAUDE_CODE_AGENTS, CURSOR_RULES, SKILL_MD)
}


def format_names() -> list[str]:
    """Declared format names, in presentation order."""
    return list(EXTERNAL_FORMATS)


def get_format(name: str) -> ExternalFormat:
    """Look up a format by name, or raise naming the valid set."""
    try:
        return EXTERNAL_FORMATS[name]
    except KeyError:
        raise ExportRefused(
            f"unknown external format {name!r} (known: {', '.join(EXTERNAL_FORMATS)})"
        ) from None


#: A destination under Claude Code's own config directory. Claude Code reads that directory from
#: ``$CLAUDE_CONFIG_DIR`` when it is set, so ``~/.claude`` spelled out would be a directory it
#: never reads.
_CLAUDE_CONFIG_PREFIX = "~/.claude/"


def default_dest_dir(fmt: ExternalFormat) -> Path | None:
    """The canonical destination directory a UI may PREFILL, or ``None``.

    Home-anchored formats resolve against ``Path.home()`` — except a destination in Claude Code's
    config directory, which resolves where Claude Code itself looks: ``$CLAUDE_CONFIG_DIR``, else
    ``~/.claude`` (``onboarding_import.sources.claude_code.resolve_root``, the reader the importer
    uses). Project-relative ones (Cursor rules, a skills plugin dir) have no machine-independent
    default, so they return ``None`` and the caller must supply a directory. This is the single
    resolver a test monkeypatches — nothing else in this module reads ``Path.home()``, so a test
    can never reach a real ``~/.claude``. Suggesting a directory is NOT confirming it:
    :func:`export_entities` still demands ``confirm_dest=True``.
    """
    if fmt.dest.startswith(_CLAUDE_CONFIG_PREFIX):
        from personalclaw.onboarding_import.sources import claude_code

        rest = PurePosixPath(fmt.dest[len(_CLAUDE_CONFIG_PREFIX) :]).parent
        return claude_code.resolve_root() / rest
    if not fmt.dest.startswith("~/"):
        return None
    return Path.home() / PurePosixPath(fmt.dest[2:]).parent


# ── Write path ────────────────────────────────────────────────────────────────


def _resolve_target(dest_dir: Path, relpath: str) -> Path:
    """Second containment check: the resolved target must live under ``dest_dir``."""
    pure = PurePosixPath(relpath)
    if not relpath or pure.is_absolute() or "\\" in relpath:
        raise ExportPathRefused(f"rendered path must be relative POSIX: {relpath!r}")
    if any(part in ("", ".", "..") for part in pure.parts):
        raise ExportPathRefused(f"rendered path may not traverse: {relpath!r}")
    if str(pure) != relpath:
        # ``./x.md``, ``a//b`` and ``a/b/`` all normalise to something SAFE, so this is not a
        # traversal — but an un-normalised path means two renderers could name one target
        # two ways, and then "did we write this file?" stops having one answer.
        raise ExportPathRefused(f"rendered path must be normalised: {relpath!r}")
    base = dest_dir.resolve()
    target = (base / pure).resolve()
    if target != base and base not in target.parents:
        raise ExportPathRefused(f"rendered path escapes {base}: {relpath!r}")
    return target


#: What writing one rendered file would do where it lands. Plain strings like the install kinds
#: above, and every one is produced by :func:`_file_state`.
FILE_NEW = "new"  # nothing is there yet
FILE_SAME = "same"  # an earlier export of ours, byte-identical: left as it is
FILE_REPLACE = "replace"  # an earlier export of ours that differs: replaced
FILE_THEIRS = "theirs"  # a file PersonalClaw did not write: the whole export is refused


def _file_state(target: Path, text: str) -> str:
    """What writing ``text`` to ``target`` would do there — the one rule the preview and the write
    share.

    A file is ours when it carries :data:`PROVENANCE_MARKER`. One that cannot be read cannot be
    shown to be ours, so it is refused like any other file PersonalClaw did not write (fail
    closed): a directory, an unreadable file, and a user's own agent all land on
    :data:`FILE_THEIRS`.
    """
    if not target.exists() and not target.is_symlink():
        return FILE_NEW
    try:
        existing = target.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return FILE_THEIRS
    if PROVENANCE_MARKER not in existing:
        return FILE_THEIRS
    return FILE_SAME if existing == text else FILE_REPLACE


@dataclass(frozen=True)
class _PlannedFile:
    relpath: str
    target: Path
    text: str
    state: str
    entities: tuple[str, ...]


@dataclass(frozen=True)
class _ExportPlan:
    """Everything an export decides before it writes a byte."""

    format_name: str
    dest_dir: Path
    files: list[_PlannedFile]
    blocked: list[BlockedRender]

    def refusal(self) -> ExportRefused | None:
        """Why this plan may not be written, or ``None``. A credential first — it must never land
        anywhere — then every file in the way at once."""
        if self.blocked:
            return ExportBlocked(self.blocked)
        theirs = [f.target for f in self.files if f.state == FILE_THEIRS]
        return ExportClobberRefused(theirs) if theirs else None


def _plan(fmt: ExternalFormat, entities: Sequence[Entity], dest_dir: Path | str) -> _ExportPlan:
    """Render, contain every path, read what is at each target, scan every text. Writes nothing.

    The order is the rails': a rendered path is contained before anything at it is read, and the
    content scan runs over every file before any refusal is decided.
    """
    root = Path(dest_dir).expanduser()
    if root.exists() and not root.is_dir():
        raise ExportPathRefused(f"The destination is not a folder: {root}")
    rendered = fmt.render(entities)
    files: list[_PlannedFile] = []
    for rf in rendered:
        target = _resolve_target(root, rf.relpath)
        files.append(
            _PlannedFile(rf.relpath, target, rf.text, _file_state(target, rf.text), rf.entities)
        )
    return _ExportPlan(fmt.name, root, files, scan_rendered(rendered))


def scan_rendered(files: Sequence[RenderedFile]) -> list[BlockedRender]:
    """Run the CONTENT layer over rendered output.

    Imports :func:`packs.build._scan_component` on purpose: the content rules are SHARED, not
    forked. Whatever blocks a pack component blocks an outbound render, and a rule added
    there applies here the same day.
    """
    from personalclaw.packs.build import _scan_component

    blocked: list[BlockedRender] = []
    for rf in files:
        reason, categories = _scan_component(rf.text.encode("utf-8"))
        if reason:
            blocked.append(BlockedRender(rf.relpath, reason, tuple(categories)))
    return blocked


def export_entities(
    fmt: ExternalFormat,
    entities: Sequence[Entity],
    dest_dir: Path | str,
    *,
    confirm_dest: bool = False,
) -> ExportResult:
    """Render ``entities`` through ``fmt`` and write them under ``dest_dir``.

    The order is deliberate and all-or-nothing: render → containment-check every path →
    read what is at every target → scan every rendered text → refuse → only then write. A
    blocked credential or one foreign file aborts the whole export, so a refusal can never
    leave the recipient tool holding half a roster.

    ``confirm_dest`` must be ``True``: we are writing into a directory another tool owns,
    and nothing is ever auto-installed there. An earlier export of ours (it carries
    :data:`PROVENANCE_MARKER`) is replaced when it differs and left alone when it does not;
    a file we did not write is always refused. The plan is made again here rather than taken
    from a preview, so what is on the disk NOW decides.

    Each file is written atomically (temp file + rename), so the recipient never reads half of
    one. A write that fails part-way raises :class:`ExportWriteFailed` naming what was written.
    """
    if not confirm_dest:
        raise DestNotConfirmed(
            f"export to {dest_dir} requires explicit destination confirmation "
            "(confirm_dest=True) — an external tool's directory is never written implicitly"
        )
    plan = _plan(fmt, entities, dest_dir)
    refusal = plan.refusal()
    if refusal is not None:
        raise refusal
    # Only now, with every check passed, does anything reach the disk: the destination is another
    # tool's folder, and a refused export must not leave one there it created. `atomic_write`
    # makes the parent folder with the first file.
    result = ExportResult(plan.format_name, plan.dest_dir)
    for planned in plan.files:
        if planned.state == FILE_SAME:
            result.unchanged.append(planned.target)
            continue
        try:
            atomic_write(planned.target, planned.text)
        except OSError as exc:
            raise ExportWriteFailed(planned.target, result.written, exc) from exc
        result.written.append(planned.target)
    return result


def export_preview(
    fmt: ExternalFormat, entities: Sequence[Entity], dest_dir: Path | str
) -> dict[str, Any]:
    """Look before you write: what an export to ``dest_dir`` WOULD do, without writing.

    The same plan the write makes (:func:`_plan`), so a UI can show where each file lands, what
    writing it would do there, any file the content scan holds back, and ``refusal`` — the
    sentence the write would refuse with, or ``None`` — before asking the user to confirm the
    destination.
    """
    plan = _plan(fmt, entities, dest_dir)
    refusal = plan.refusal()
    return {
        "format": plan.format_name,
        "dest": str(plan.dest_dir),
        "files": [
            {"path": f.relpath, "state": f.state, "entities": list(f.entities)} for f in plan.files
        ],
        "blocked": [{"path": b.relpath, "categories": list(b.categories)} for b in plan.blocked],
        "refusal": str(refusal) if refusal is not None else None,
    }
