#!/usr/bin/env python3
"""One consolidated record per atom, in one place, regenerable — ``docs/roadmap/atoms/``.

Why this exists
---------------
An atom's state was scattered across at least six surfaces, and they disagreed. Measured on
``2ec3ae86e``: ``dag.json`` said 684 atoms / 650 done, ``atomic/README.md`` said 640 / 356,
and ``roadmap-dashboard.html`` said 648 / "146 remaining" — three different answers to *how
much of this project is finished*, none of them agreeing. Beyond the counts, answering "what
is the real state of `PP-16`?" meant reading `dag.json`, then `atomic/PP.md`, then the source
plan's execution log, then `git log`, then the dashboard, then any design note that mentions
it — and knowing which to believe when they conflict.

This tool collapses that into ONE file per atom that names its own provenance for every
claim, so a reader never has to guess which surface is authoritative.

**It is a projection, never a source.** Every byte is rendered from committed inputs:

* ``docs/roadmap/atomic/dag.json``    — identity, status, scope, done_when, deps (authored)
* ``docs/roadmap/atoms/evidence.json`` — git-derived commit history (a refreshed CACHE)
* ``docs/roadmap/atoms/verdicts.json`` — audit + UI-validation verdicts (authored by the audit loop)
* ``docs/roadmap/plans/*.md``          — the source plans' execution logs
* ``docs/roadmap/design-notes/*.md``, ``docs/roadmap/research/*.md``

Editing a generated ``<ID>.md`` by hand is therefore always wrong: the next run discards it.
Put the fact in the input that owns it — a status in ``dag.json``, a verdict in
``verdicts.json`` — and regenerate.

    python3 tools/gen_atom_records.py                # render every atom record + INDEX
    python3 tools/gen_atom_records.py --check        # exit 1 if any committed record is stale
    python3 tools/gen_atom_records.py --refresh-git  # re-scan git history into evidence.json
    python3 tools/gen_atom_records.py --atom PP-16   # render one, to stdout

🪤 WHY GIT HISTORY IS A COMMITTED CACHE AND NOT SCANNED ON EVERY RUN. CI checks out with
``actions/checkout@v7``, which is **shallow by default** — ``git log`` there sees one commit.
A generator that read history live would render one corpus locally and a different one in CI,
so ``--check`` would red on every PR for a reason that has nothing to do with the change. The
cache makes every rendered byte a function of committed files only, which is what lets the
ratchet be an exact byte comparison. ``--refresh-git`` is the deliberate act that updates it,
and it requires a repository with history (it refuses a shallow clone rather than silently
writing an empty cache).
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

CORE = Path(__file__).resolve().parents[1]
ROADMAP = CORE / "docs/roadmap"
DAG_PATH = ROADMAP / "atomic/dag.json"
ATOMS_DIR = ROADMAP / "atoms"
EVIDENCE_PATH = ATOMS_DIR / "evidence.json"
VERDICTS_PATH = ATOMS_DIR / "verdicts.json"
INDEX_PATH = ATOMS_DIR / "INDEX.md"

#: Directories whose prose is scanned for atom mentions, each with the label used in the record.
PROSE_SOURCES = (
    ("plans", "source plan"),
    ("design-notes", "design note"),
    ("research", "research"),
)
#: A generated record opens with this, so a hand edit is obviously going to be discarded.
BANNER = (
    "<!-- GENERATED by tools/gen_atom_records.py — do not edit. Every claim below is"
    " rendered from a committed input; edit that input and regenerate. -->"
)
REMEDY = "run `python3 tools/gen_atom_records.py` and commit the result"
#: Verdict values the audit loop may record. `unaudited` is the default for an atom nobody
#: has checked yet — it is deliberately distinct from `unverifiable`, which is a CONCLUSION.
VERDICTS = ("unaudited", "confirmed", "partial", "contradicted", "unverifiable")


def load_json(path: Path, default: object) -> object:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def load_verdicts(known: set[str]) -> dict[str, dict]:
    """Read ``verdicts.json``, refusing a typo'd atom id or an unknown verdict value.

    A verdict filed against ``PP-61`` instead of ``PP-16`` would otherwise sit in the file
    forever, silently attached to nothing, while the atom it was meant for still read
    ``unaudited`` — the audit would look done and would not be. Keys beginning ``_`` are
    documentation, not verdicts.
    """
    raw = load_json(VERDICTS_PATH, {})
    if not isinstance(raw, dict):
        raise SystemExit(f"{VERDICTS_PATH}: expected an object mapping atom id -> verdict")
    out: dict[str, dict] = {}
    for key, value in raw.items():
        if key.startswith("_"):
            continue
        if key not in known:
            raise SystemExit(
                f"{VERDICTS_PATH}: {key!r} names no atom in dag.json — a verdict filed against"
                " a typo'd id is attached to nothing and leaves the real atom unaudited"
            )
        state = (value or {}).get("verdict")
        if state not in VERDICTS:
            raise SystemExit(
                f"{VERDICTS_PATH}: {key} has verdict {state!r}, not one of {', '.join(VERDICTS)}"
            )
        out[key] = value
    return out


def atom_id_pattern(atom_ids: list[str]) -> re.Pattern[str]:
    """One alternation over the real ids, longest first, with digit-safe boundaries.

    🪤 ``\\bAR-1\\b`` alone would match inside ``AR-15`` on some engines depending on what
    follows, and a plain ``\\b`` after a digit does NOT stop ``AR-1`` matching the ``AR-1``
    prefix of ``AR-15`` when the alternation is unordered. Sorting longest-first makes the
    alternation prefer ``AR-15``, and the trailing ``(?!\\d)`` makes a short id refuse a
    longer number outright. Both are needed: the sort fixes which alternative wins, the
    lookahead fixes the case where only the short id is in the pattern at all.
    """
    ordered = sorted(atom_ids, key=len, reverse=True)
    return re.compile(r"\b(" + "|".join(re.escape(i) for i in ordered) + r")(?!\d)")


def scan_prose(atom_ids: list[str]) -> dict[str, list[dict]]:
    """Every mention of every atom id in the roadmap's prose, with file + line provenance."""
    pattern = atom_id_pattern(atom_ids)
    found: dict[str, list[dict]] = defaultdict(list)
    for subdir, label in PROSE_SOURCES:
        root = ROADMAP / subdir
        if not root.is_dir():
            continue
        for path in sorted(root.glob("*.md")):
            rel = path.relative_to(CORE).as_posix()
            for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
                stripped = line.strip()
                if not stripped:
                    continue
                for aid in set(pattern.findall(stripped)):
                    found[aid].append(
                        {"kind": label, "file": rel, "line": lineno, "text": stripped}
                    )
    return found


#: Task/section tokens an atom's ``scope`` uses to point into its source plan. An atom id is
#: NOT how the plan refers to its own work: the plans predate the decomposition and number
#: their tasks ``T1.1`` / ``§2.3`` / ``Session 4``, so `AE-1`'s scope reads "Session 1 T1.1"
#: and the plan's execution log says ``T1.1``. Scanning for `AE-1` therefore finds NOTHING —
#: measured, 211 of the 650 done atoms had zero prose mentions and zero commits, which reads
#: as "no evidence this landed" when the real record was filed under another name the whole
#: time. These patterns are the translation.
#: 🔑 AND THE VOCABULARY IS NOT ONE VOCABULARY — it is per-plan, which is why the first pass
#: still left 11 atoms with no record at all. `WV` numbers its work as ``Slice 0``, `DSC` as
#: ``cy51`` cycles and ``G1``–``G9`` batches, `MRI` as ``G1.1-G1.4``, `WF2LOO` as ``R8``. Each
#: family had to be READ off the atoms that came up empty; there is no general rule to infer.
SCOPE_REF_RES = (
    re.compile(r"\bT\d+\.\d+[a-z]?\b"),  # T1.1, T12.3b — the plans' task numbering
    re.compile(r"§\d+(?:\.\d+)*"),  # §1, §2.3 — section references
    re.compile(r"\bSession \d+[a-z]?\b"),  # Session 1, Session 5b
    re.compile(r"\bSlice \d+\b"),  # Slice 0 — WORKFLOWS-V2's unit of work
    re.compile(r"\bcy\d+\b"),  # cy51 — DESIGN-SYSTEM-CONSISTENCY's cycles
    re.compile(r"\bG\d+(?:\.\d+)?\b"),  # G1, G1.4 — gate/batch ids (DSC, MRI)
    re.compile(r"\bR\d+\b"),  # R8 — WF2LOO's ruling ids
)
#: Cap per token, so one atom citing `§1` does not paste a whole plan into its record.
SCOPE_REF_CAP = 8


def scope_refs(atom: dict) -> list[str]:
    """The task/section tokens an atom's ``scope`` names, de-duplicated, order preserved."""
    text = atom.get("scope") or ""
    seen: list[str] = []
    for pattern in SCOPE_REF_RES:
        for token in pattern.findall(text):
            if token not in seen:
                seen.append(token)
    return seen


def scan_scope_refs(ctx: dict) -> dict[str, list[dict]]:
    """For each atom, the lines of ITS OWN plan that carry the tokens its scope cites.

    Scoped to the atom's own plan file deliberately: ``T1.1`` exists in most plans, so a
    repo-wide search for it would attach forty unrelated plans' task lines to every atom.
    """
    plan_text: dict[str, list[str]] = {}
    out: dict[str, list[dict]] = defaultdict(list)
    for aid, atom in ctx["by_id"].items():
        tokens = scope_refs(atom)
        if not tokens:
            continue
        name = ctx["plan_of"][aid].get("plan")
        path = ROADMAP / "plans" / f"{name}.md"
        if not path.exists():
            continue
        if name not in plan_text:
            plan_text[name] = path.read_text(encoding="utf-8").splitlines()
        rel = path.relative_to(CORE).as_posix()
        for token in tokens:
            hits = 0
            for lineno, line in enumerate(plan_text[name], 1):
                stripped = line.strip()
                if token not in stripped:
                    continue
                out[aid].append({"token": token, "file": rel, "line": lineno, "text": stripped})
                hits += 1
                if hits >= SCOPE_REF_CAP:
                    break
    return out


def refresh_git_evidence(atom_ids: list[str]) -> dict[str, list[dict]]:
    """Scan full git history once for atom-id mentions in commit subjects and bodies."""
    depth = subprocess.run(
        ["git", "rev-parse", "--is-shallow-repository"],
        cwd=CORE,
        capture_output=True,
        text=True,
    )
    if depth.stdout.strip() == "true":
        raise SystemExit(
            "refusing to refresh git evidence from a SHALLOW clone — the cache would be a"
            " near-empty file that then reds --check everywhere. Run in a full clone"
            " (`git fetch --unshallow`)."
        )
    sep = "\x1e"
    proc = subprocess.run(
        ["git", "log", "--no-merges", f"--format=%H{sep}%ad{sep}%s{sep}%b{sep}", "--date=short"],
        cwd=CORE,
        capture_output=True,
        text=True,
        check=True,
    )
    pattern = atom_id_pattern(atom_ids)
    out: dict[str, list[dict]] = defaultdict(list)
    for record in proc.stdout.split(f"{sep}\n"):
        parts = record.split(sep)
        if len(parts) < 4:
            continue
        sha, date, subject, body = parts[0].strip(), parts[1], parts[2], parts[3]
        if not sha:
            continue
        # The SUBJECT is what a reader wants; the body is searched so an atom mentioned only
        # in a trailer or explanation is still credited to the commit that did the work.
        for aid in sorted(set(pattern.findall(f"{subject}\n{body}"))):
            out[aid].append({"sha": sha[:9], "date": date, "subject": subject})
    return {k: v for k, v in sorted(out.items())}


def build_context(data: dict) -> dict:
    """Everything the renderer needs that is derived from the catalog rather than one atom."""
    plans = data["plans"]
    dag = data.get("dag") or {}
    by_id: dict[str, dict] = {}
    plan_of: dict[str, dict] = {}
    for plan in plans:
        for atom in plan.get("atoms") or []:
            by_id[atom["id"]] = atom
            plan_of[atom["id"]] = plan
    dependents: dict[str, list[str]] = defaultdict(list)
    for aid, atom in by_id.items():
        for dep in atom.get("deps") or []:
            if dep in by_id:
                dependents[dep].append(aid)
    topo = dag.get("topo_order") or []
    ext_resolution: dict[str, list[dict]] = defaultdict(list)
    for edge in dag.get("resolved_edges") or []:
        ext_resolution[edge.get("atom", "")].append(edge)
    return {
        "by_id": by_id,
        "plan_of": plan_of,
        "dependents": {k: sorted(v) for k, v in dependents.items()},
        "topo_index": {aid: i + 1 for i, aid in enumerate(topo)},
        "topo_total": len(topo),
        "ready": {e["id"] for e in dag.get("ready_frontier") or []},
        "gated": {e["id"]: e.get("gate") or [] for e in dag.get("gated_frontier") or []},
        "cycles": dag.get("cycles") or [],
        "ext_resolution": ext_resolution,
    }


def frontier_line(aid: str, atom: dict, ctx: dict) -> str:
    if atom.get("status") == "done":
        return "landed"
    if aid in ctx["ready"]:
        return "**startable** — every intra-repo dependency is done and nothing gates it"
    if aid in ctx["gated"]:
        gates = ", ".join(f"`{g}`" for g in ctx["gated"][aid])
        return f"dependency-satisfied but **gated** ({gates})"
    unmet = [
        d
        for d in atom.get("deps") or []
        if d in ctx["by_id"] and ctx["by_id"][d].get("status") != "done"
    ]
    if unmet:
        return f"waiting on {len(unmet)} unfinished dependency: " + ", ".join(
            f"`{d}`" for d in unmet
        )
    return "not startable"


def render(aid: str, ctx: dict, prose: dict, scope_of: dict, evidence: dict, verdicts: dict) -> str:
    atom = ctx["by_id"][aid]
    plan = ctx["plan_of"][aid]
    status = atom.get("status", "?")
    lines = [
        BANNER,
        "",
        f"# `{aid}` — {atom.get('title', '')}",
        "",
        "| | |",
        "|---|---|",
        f"| **Status** | `{status}` |",
        f"| **Plan** | [{plan.get('plan')}](../plans/{plan.get('plan')}.md)"
        f" (`{plan.get('code')}`, plan status `{plan.get('status')}`) |",
        f"| **Atom table** | [`../atomic/{plan.get('code')}.md`]"
        f"(../atomic/{plan.get('code')}.md) |",
        f"| **Execution position** | #{ctx['topo_index'].get(aid, '?')}"
        f" of {ctx['topo_total']} in dependency order |",
        f"| **Startability** | {frontier_line(aid, atom, ctx)} |",
    ]
    if atom.get("blocked_reason"):
        lines.append(f"| **Blocked reason** | {atom['blocked_reason']} |")
    if atom.get("pr"):
        lines.append(f"| **PR** | #{atom['pr']} |")

    lines += [
        "",
        "## Intent — what this is for",
        "",
        (atom.get("scope") or "_No scope recorded in `dag.json`._").strip(),
        "",
        "## Done when",
        "",
        (atom.get("done_when") or "_No `done_when` recorded in `dag.json`._").strip(),
        "",
    ]

    deps = atom.get("deps") or []
    lines += ["## Dependencies", ""]
    if not deps:
        lines.append("_None — this atom has no declared dependency._")
    else:
        lines += ["| Depends on | Kind | Status |", "|---|---|---|"]
        for dep in deps:
            if dep in ctx["by_id"]:
                lines.append(
                    f"| [`{dep}`]({dep}.md) | intra-repo | `{ctx['by_id'][dep].get('status')}` |"
                )
            elif str(dep).startswith("EXT:"):
                # An EXT ref is prose naming a cross-plan contract. Its resolution to a real
                # atom is AUTHORED in dag.json's resolved_edges, so show it when it exists —
                # an unresolved one is a genuinely open question, not a rendering gap.
                target = next(
                    (
                        e.get("to_atom")
                        for e in ctx["ext_resolution"].get(aid, [])
                        if e.get("dep") == dep
                    ),
                    None,
                )
                shown = f"resolved → [`{target}`]({target}.md)" if target else "**unresolved**"
                lines.append(f"| `{dep}` | cross-plan (EXT) | {shown} |")
            else:
                lines.append(f"| `{dep}` | **dangling — names no known atom** | — |")
    dependents = ctx["dependents"].get(aid) or []
    lines += ["", f"### Unblocks ({len(dependents)})", ""]
    if dependents:
        lines.append(
            ", ".join(f"[`{d}`]({d}.md) (`{ctx['by_id'][d].get('status')}`)" for d in dependents)
        )
    else:
        lines.append("_Nothing depends on this atom._")

    in_cycle = [c for c in ctx["cycles"] if aid in c]
    if in_cycle:
        lines += [
            "",
            "### ⚠️ In a dependency cycle",
            "",
            "This atom sits in a cross-plan cycle, so no execution order can satisfy it"
            " as declared — the cycle has to be broken by a scope decision:",
            "",
        ]
        lines += [f"- `{' → '.join(c)}`" for c in in_cycle]

    verdict = verdicts.get(aid) or {}
    state = verdict.get("verdict", "unaudited")
    lines += [
        "",
        "## Verification",
        "",
        f"**Audit verdict:** `{state}`",
    ]
    if state == "unaudited":
        lines += [
            "",
            "_No one has checked this atom's `done_when` against the code yet._ A verdict is"
            " recorded in [`verdicts.json`](verdicts.json), never by editing this file.",
        ]
    else:
        for label, key in (
            ("Checked on", "date"),
            ("Checked by", "by"),
            ("Code evidence", "evidence"),
            ("Driven in the UI", "ui_validated"),
            ("Notes", "notes"),
        ):
            if verdict.get(key):
                value = verdict[key]
                if isinstance(value, list):
                    lines += ["", f"**{label}:**", ""] + [f"- {v}" for v in value]
                else:
                    lines += ["", f"**{label}:** {value}"]
        if verdict.get("follow_ups"):
            lines += ["", "**Follow-ups filed:**", ""]
            lines += [f"- {f}" for f in verdict["follow_ups"]]

    commits = evidence.get(aid) or []
    lines += ["", "## Recorded history", "", f"### Commits ({len(commits)})", ""]
    if commits:
        lines += [f"- `{c['sha']}` {c['date']} — {c['subject']}" for c in commits]
    else:
        lines.append(
            "_No commit names this atom._ For a `done` atom that is worth a second look:"
            " the work may have landed under a different id, or the status may be wrong."
        )

    mentions = prose.get(aid) or []
    lines += ["", f"### Named by atom id in the roadmap prose ({len(mentions)})", ""]
    if mentions:
        for m in mentions:
            text = m["text"]
            if len(text) > 300:
                text = text[:297] + "…"
            lines.append(f"- **{m['kind']}** `{m['file']}:{m['line']}` — {text}")
    else:
        lines.append(
            "_No prose names this atom by id._ That is normal rather than suspicious: the"
            " source plans predate the decomposition and refer to their own work by task"
            " number, so the record is usually under the scope references below."
        )

    refs = scope_of.get(aid) or []
    tokens = scope_refs(atom)
    lines += [
        "",
        f"### Its plan's own record, via the scope references ({len(refs)} line(s))",
        "",
    ]
    if refs:
        lines.append(
            "This atom's scope cites " + ", ".join(f"`{t}`" for t in tokens) + ". Those"
            " tokens appear in its source plan at:"
        )
        lines.append("")
        for m in refs:
            text = m["text"]
            if len(text) > 300:
                text = text[:297] + "…"
            lines.append(f"- `{m['token']}` `{m['file']}:{m['line']}` — {text}")
    elif tokens:
        lines.append(
            "Its scope cites "
            + ", ".join(f"`{t}`" for t in tokens)
            + ", but no line of its source plan carries any of them."
        )
    else:
        lines.append("_Its scope names no task or section token to resolve._")

    lines += [
        "",
        "---",
        "",
        "_Rendered from `docs/roadmap/atomic/dag.json` (identity, status, scope, deps),"
        " `evidence.json` (git history), `verdicts.json` (audit verdicts) and the roadmap"
        " prose. Regenerate with `python3 tools/gen_atom_records.py`._",
    ]
    return "\n".join(lines) + "\n"


def render_index(ctx: dict, verdicts: dict, evidence: dict) -> str:
    by_id = ctx["by_id"]
    plans: dict[str, list[str]] = defaultdict(list)
    for aid in by_id:
        plans[ctx["plan_of"][aid]["code"]].append(aid)
    counts: dict[str, int] = defaultdict(int)
    for aid in by_id:
        counts[(verdicts.get(aid) or {}).get("verdict", "unaudited")] += 1
    lines = [
        BANNER,
        "",
        "# Atom records — one consolidated file per atom",
        "",
        f"**{len(by_id)} atoms** across **{len(plans)} plans**. One file each, holding every"
        " recorded fact about that atom with the provenance of each claim: its intent, its"
        " `done_when` contract, its dependencies and dependents, the commits that name it,"
        " every roadmap-prose mention, and its audit verdict.",
        "",
        "## Why these files exist",
        "",
        "An atom's state used to be spread over `dag.json`, `atomic/<CODE>.md`, the source"
        " plan's execution log, git history, the dashboard and any design note that"
        " mentioned it — and those surfaces disagreed. Measured on `2ec3ae86e` the three"
        " headline counts were **684 / 650 done** (`dag.json`), **640 / 356 done**"
        " (`atomic/README.md`) and **648 / 146 remaining** (the dashboard): three different"
        " answers to how finished the project is. These records are the single place to"
        " look, and they are a **projection** — never edit one by hand.",
        "",
        "## Audit coverage",
        "",
        "| Verdict | Atoms | Meaning |",
        "|---|---|---|",
        f"| `confirmed` | {counts['confirmed']} | `done_when` checked against the code"
        " and it holds |",
        f"| `partial` | {counts['partial']} | some `done_when` clauses hold, others do not |",
        f"| `contradicted` | {counts['contradicted']} | the recorded status disagrees with"
        " the code |",
        f"| `unverifiable` | {counts['unverifiable']} | cannot be settled here (needs"
        " hardware, a paid key, an owner action) |",
        f"| `unaudited` | {counts['unaudited']} | not yet checked |",
        "",
        "## Atoms without a single commit naming them",
        "",
        "A `done` atom that no commit mentions is the highest-yield place to look for a wrong"
        " status — either the work landed under another id, or it did not land.",
        "",
    ]
    orphan_done = sorted(
        aid
        for aid, atom in by_id.items()
        if atom.get("status") == "done" and not (evidence.get(aid) or [])
    )
    if orphan_done:
        lines.append(
            f"{len(orphan_done)} of them: "
            + ", ".join(f"[`{a}`]({a}.md)" for a in orphan_done[:60])
            + (" …" if len(orphan_done) > 60 else "")
        )
    else:
        lines.append("_None — every `done` atom is named by at least one commit._")

    lines += ["", "## Every atom, by plan", ""]
    for code in sorted(plans):
        plan = ctx["plan_of"][plans[code][0]]
        atoms = sorted(plans[code], key=lambda a: int(a.rsplit("-", 1)[1]))
        done = sum(1 for a in atoms if by_id[a].get("status") == "done")
        lines += [
            f"### `{code}` — {plan.get('plan')} ({done}/{len(atoms)} done)",
            "",
            "| Atom | Status | Verdict | Title |",
            "|---|---|---|---|",
        ]
        for aid in atoms:
            atom = by_id[aid]
            v = (verdicts.get(aid) or {}).get("verdict", "unaudited")
            title = (atom.get("title") or "").replace("|", "\\|")
            lines.append(f"| [`{aid}`]({aid}.md) | `{atom.get('status')}` | `{v}` | {title} |")
        lines.append("")
    return "\n".join(lines) + "\n"


def render_all(data: dict) -> dict[str, str]:
    ctx = build_context(data)
    atom_ids = sorted(ctx["by_id"])
    prose = scan_prose(atom_ids)
    evidence = load_json(EVIDENCE_PATH, {})
    verdicts = load_verdicts(set(ctx["by_id"]))
    scope_of = scan_scope_refs(ctx)
    out = {f"{aid}.md": render(aid, ctx, prose, scope_of, evidence, verdicts) for aid in atom_ids}
    out["INDEX.md"] = render_index(ctx, verdicts, evidence)
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if any record is stale")
    parser.add_argument(
        "--refresh-git", action="store_true", help="re-scan git history into evidence.json"
    )
    parser.add_argument("--atom", help="render one atom to stdout and exit")
    parser.add_argument("--out", type=Path, default=ATOMS_DIR, help="output directory")
    args = parser.parse_args(argv)

    data = json.loads(DAG_PATH.read_text(encoding="utf-8"))
    if "plans" not in data:
        raise SystemExit(f"{DAG_PATH}: no 'plans' key — is this the atomic plan catalog?")

    if args.refresh_git:
        ctx = build_context(data)
        fresh = refresh_git_evidence(sorted(ctx["by_id"]))
        EVIDENCE_PATH.parent.mkdir(parents=True, exist_ok=True)
        EVIDENCE_PATH.write_text(
            json.dumps(fresh, indent=1, ensure_ascii=False, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        named = sum(len(v) for v in fresh.values())
        print(f"{EVIDENCE_PATH.name}: {len(fresh)} atoms named by {named} commit mention(s)")

    if args.atom:
        ctx = build_context(data)
        if args.atom not in ctx["by_id"]:
            raise SystemExit(f"unknown atom {args.atom!r}")
        prose = scan_prose(sorted(ctx["by_id"]))
        print(
            render(
                args.atom,
                ctx,
                prose,
                scan_scope_refs(ctx),
                load_json(EVIDENCE_PATH, {}),
                load_verdicts(set(ctx["by_id"])),
            ),
            end="",
        )
        return 0

    rendered = render_all(data)
    args.out.mkdir(parents=True, exist_ok=True)
    committed = {p.name: p.read_text(encoding="utf-8") for p in args.out.glob("*.md")}
    stale = sorted(n for n, text in rendered.items() if committed.get(n) != text)
    orphaned = sorted(set(committed) - set(rendered))

    if not stale and not orphaned:
        print(f"{args.out.name}/: {len(rendered)} records already current")
        return 0
    if args.check:
        detail = ", ".join(stale[:8]) + (" …" if len(stale) > 8 else "")
        extra = f"; {len(orphaned)} orphaned ({', '.join(orphaned[:5])})" if orphaned else ""
        print(
            f"{args.out}: {len(stale)} record(s) stale{extra} — {detail} — {REMEDY}",
            file=sys.stderr,
        )
        return 1
    for name, text in rendered.items():
        (args.out / name).write_text(text, encoding="utf-8")
    for name in orphaned:
        # An atom removed from dag.json must not leave a record claiming it still exists.
        (args.out / name).unlink()
    print(
        f"{args.out.name}/: wrote {len(stale)} record(s)"
        + (f", removed {len(orphaned)} orphaned" if orphaned else "")
        + f" ({len(rendered)} total)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
